#!/bin/zsh

# =============================================================================
# generate-aliases.sh
# Generates shell aliases for quick navigation between baúles (vaults)
# 
# Usage (to activate aliases immediately): 
#   source _scripts/generate-aliases.sh
#
# Alternative (requires manual activation):
#   ./_scripts/generate-aliases.sh
#   source ~/.zshrc
# =============================================================================

# Get the directory where life-os lives WITHOUT using cd (to avoid nvm hook)
SCRIPT_DIR="${0:a:h}"
LIFE_OS_ROOT="${SCRIPT_DIR:h}"
ALIASES_FILE="$LIFE_OS_ROOT/.life-os-aliases"

echo "🧠 Generating Life-OS aliases..."
echo ""

# Start fresh - write header
echo "# =============================================================================" > "$ALIASES_FILE"
echo "# Life-OS Vault Navigation Aliases" >> "$ALIASES_FILE"
echo "# Auto-generated by generate-aliases.sh" >> "$ALIASES_FILE"
echo "# DO NOT EDIT MANUALLY - Re-run the script to update" >> "$ALIASES_FILE"
echo "# =============================================================================" >> "$ALIASES_FILE"
echo "" >> "$ALIASES_FILE"

# Add the root alias
echo "# Quick access to Life-OS root" >> "$ALIASES_FILE"
echo "alias lifeos=\"cd $LIFE_OS_ROOT\"" >> "$ALIASES_FILE"
echo "" >> "$ALIASES_FILE"
echo "# Vault aliases" >> "$ALIASES_FILE"

# Counter for vaults found
count=0

# Find all directories, excluding those starting with . or _
for dir in "$LIFE_OS_ROOT"/*/; do
    # Check if directory exists (handles case of no matches)
    [[ -d "$dir" ]] || continue
    
    # Get just the folder name
    folder_name="${dir:t:r}"
    
    # Skip if starts with . or _
    if [[ "$folder_name" == .* ]] || [[ "$folder_name" == _* ]]; then
        continue
    fi
    
    # Generate the alias
    echo "alias $folder_name=\"cd $LIFE_OS_ROOT/$folder_name\"" >> "$ALIASES_FILE"
    echo "  ✓ $folder_name"
    ((count++))
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Generated $count vault aliases + 'lifeos' root alias"
echo "📄 File: $ALIASES_FILE"
echo ""

# Auto-add to .zshrc if not already present
ZSHRC_FILE="$HOME/.zshrc"
SOURCE_LINE="source $ALIASES_FILE"

if grep -q "life-os-aliases" "$ZSHRC_FILE" 2>/dev/null; then
    echo "🔗 Already integrated with ~/.zshrc"
else
    echo "" >> "$ZSHRC_FILE"
    echo "# Life-OS vault navigation aliases" >> "$ZSHRC_FILE"
    echo "$SOURCE_LINE" >> "$ZSHRC_FILE"
    echo "🔗 Added to ~/.zshrc automatically"
fi

# Automatically source the aliases file to activate them now
source "$ALIASES_FILE"
echo "⚡ Aliases activated in current shell!"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 Done! Try typing 'vocabulary' or 'lifeos' now."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
