#!/bin/bash

# =============================================================================
# generate-aliases.sh
# Generates shell aliases for quick navigation between baúles (vaults)
# 
# Usage: 
#   1. Run this script: ./_scripts/generate-aliases.sh
#   2. Add to your ~/.zshrc: source /path/to/life-os/.life-os-aliases
#   3. Restart terminal or run: source ~/.zshrc
# =============================================================================

# Get the directory where life-os lives (parent of _scripts)
LIFE_OS_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ALIASES_FILE="$LIFE_OS_ROOT/.life-os-aliases"

echo "🧠 Generating Life-OS aliases..."
echo ""

# Start fresh
cat > "$ALIASES_FILE" << 'EOF'
# =============================================================================
# Life-OS Vault Navigation Aliases
# Auto-generated by generate-aliases.sh
# DO NOT EDIT MANUALLY - Re-run the script to update
# =============================================================================

EOF

# Add the root alias
echo "# Quick access to Life-OS root" >> "$ALIASES_FILE"
echo "alias lifeos=\"cd $LIFE_OS_ROOT\"" >> "$ALIASES_FILE"
echo "" >> "$ALIASES_FILE"
echo "# Vault aliases" >> "$ALIASES_FILE"

# Counter for vaults found
count=0

# Find all directories, excluding those starting with . or _
for dir in "$LIFE_OS_ROOT"/*/; do
    # Get just the folder name
    folder_name=$(basename "$dir")
    
    # Skip if starts with . or _
    if [[ "$folder_name" == .* ]] || [[ "$folder_name" == _* ]]; then
        continue
    fi
    
    # Generate the alias
    echo "alias $folder_name=\"cd $LIFE_OS_ROOT/$folder_name\"" >> "$ALIASES_FILE"
    echo "  ✓ $folder_name"
    ((count++))
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Generated $count vault aliases + 'lifeos' root alias"
echo "📄 File: $ALIASES_FILE"
echo ""
echo "📋 Next step: Add this line to your ~/.zshrc:"
echo ""
echo "   source $ALIASES_FILE"
echo ""
echo "Then run: source ~/.zshrc"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
